# Generated by Django 4.1.7 on 2023-03-19 12:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('link', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiration_datetime', models.DateTimeField(blank=True, null=True)),
                ('image', models.ForeignKey(help_text='Image', on_delete=django.db.models.deletion.CASCADE, to='images.photo')),
            ],
        ),
    ]
